<?php 
$hubVerifyToken = 'chatbotphptolotra';
$accessToken = "EAAKAx7ECniwBAPQsZBfOZCXEh74rV5R7xZCwpuogM2PumiZBPivIUWVgl9MIZAU2jzSXDEDjocZACvBKN0nIfPRUZCUUZBAHcDE9CmfpqWF3IUogpVQuZCgP0JsEIBVcyfhJzqOwS9W7PDsFWSgkNZBRcqRlvqMwGzVyekVv4D7nj81uJZCvHu4fGct";
 ?>